CODE SEGMENT
ASSUME CS:CODE
ORG 1000H
START:JMP L
DATA DB 1,2,3
L:
  MOV BX,2000H ;POINTER
  MOV AL,[BX]  ;2000H GO TO AL
  MOV CL,4
  SHL AL,CL    ;AL LEFT 4
  INC BX      ;BX = 2001H
  MOV AH,[BX]  ;2001H GO TO AH
  AND AH,0FH    ;SHUT DOWN HIGH 4 OF AH
  OR  AH,AL
  INC BX       ;2002H
  MOV [BX],AH
  MOV AH,4CH
  INT 21H
CODE ENDS
END START
