CODE SEGMENT
ASSUME CS:CODE
ORG 1000H
START:JMP L
DATA DB 3FH,06H,5BH,4FH,66H,6DH,7DH,07H,7FH,6FH,77H,7CH,39H,5EH,79H,71H
DATA1 DB ?
DATA2 DB ?
L:
   ;GET KEYBOARD
   MOV  DX,0DFH
   IN   AL,DX                                                                             `
   AND  AL,01H
   JZ   L
   MOV  CX,0FFFH
   LOOP $
   MOV  DX,0DEH
   IN   AL,DX ; WHAT IN AL IS KEY VALUE
   ;SP LOW AND HIGH
   MOV AH,AL
   AND AL,0FH
   MOV DATA1,AL
   
   MOV CL,4
   SHR AH,CL
   MOV DATA2,AH
   
   ;KEYVALUE TRANSFER TO SHOWCODE
   ;LOW BIT
   LEA BX,DATA
   MOV AH,0
   MOV AL,DATA1
   ADD BX,AX
   MOV AL,[BX]
   MOV DATA1,AL
   
   ;HIGH BIT
   LEA BX,DATA
   MOV AH,0
   MOV AL,DATA2
   ADD BX,AX
   MOV AL,[BX]
   MOV DATA2,AL
   
   ;SHOW NUMBER
   ;LOW BIT
   MOV DX,00DFH
   MOV AL,90H
   OUT DX,AL
   MOV DX,00DEH
   MOV AL,DATA1
   OUT DX,AL
   
   ;HIGH BIT
   MOV DX,00DFH
   MOV AL,91H
   OUT DX,AL
   MOV DX,00DEH
   MOV AL,DATA2
   OUT DX,AL
   
   
   ;LOOP
   JMP L
CODE ENDS
END START
